
POST http://localhost:8000/api/artem/misha
Content-Type: application/json

{
  "text": "hi"
}

###
POST http://localhost:8000/api/artem/misha
Content-Type: application/json

{
  "text": "misha"
}

###

GET http://localhost:8000/api/misha/artem
Accept: application/json

###

GET http://localhost:8000/api/artem/misha
Accept: application/json

###

DELETE http://localhost:8000/api/artem/misha
Accept: application/json

###

PUT http://localhost:8000/api/artem/misha/hi
Content-Type: application/json

{
  "text": "hello"
}